services:
  MultiTorProxy:
    container_name: MultiTorProxy
    hostname: MultiTorProxy
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    ports:
      - name: privoxy-http
        target: 8118
        host_ip: 0.0.0.0
        published: 8118
        protocol: tcp
      - name: haproxy-socks5
        target: 8050
        host_ip: 0.0.0.0
        published: 8050
        protocol: tcp
    env_file:
      - path: .env
        required: true
    restart: unless-stopped
    volumes:
      - type: volume
        source: tor-data
        target: /var/lib/tor

volumes:
  tor-data:
    driver: local
    name: MultiTorProxy_tor-data
