FROM alpine:3.7

EXPOSE 8118 9050

RUN apk --update add privoxy tor runit tini

# Default Privoxy configuration
ENV PRIVOXY_LISTEN_ADDRESS=0.0.0.0:8118
ENV PRIVOXY_FORWARD_SOCKS5=/localhost:9050
ENV PRIVOXY_TOGGLE=1
ENV PRIVOXY_ENABLE_REMOTE_TOGGLE=0
ENV PRIVOXY_ENABLE_EDIT_ACTIONS=0
ENV PRIVOXY_ENABLE_COMPRESSION=0
ENV PRIVOXY_ACCEPT_INTERCEPTED_REQUESTS=0
ENV PRIVOXY_BUFFER_LIMIT=4096
ENV PRIVOXY_ENABLE_PROXY_AUTHENTICATION_FORWARDING=0

# Default Tor configuration
ENV TOR_SOCKS_PORT=9050
ENV TOR_CONTROL_PORT=9051
ENV TOR_DNS_PORT=5353
ENV TOR_RELAY=0
ENV TOR_NICKNAME=TorPrivoxyAlpineRelay
ENV TOR_BANDWIDTH_RATE=1000000
ENV TOR_BANDWIDTH_BURST=2000000
ENV TOR_EXIT_POLICY="reject *:*"

COPY service /etc/service/

ENTRYPOINT ["tini", "--"]
CMD ["runsvdir", "/etc/service"]
