FROM alpine:3.20.3

EXPOSE 8118 9050

ARG PRIVOXY_VERSION=3.0.32-r0
ARG TOR_VERSION=0.4.7.13-r0
ARG RUNIT_VERSION=2.1.2-r7
ARG TINI_VERSION=0.19.0-r0

RUN apk --no-cache add \
  privoxy=${PRIVOXY_VERSION} \
  tor=${TOR_VERSION} \
  runit=${RUNIT_VERSION} \
  tini=${TINI_VERSION} && \
  adduser -D -u 1000 toruser

# Default Privoxy configuration
ENV PRIVOXY_LISTEN_ADDRESS=0.0.0.0:8118 \
  PRIVOXY_FORWARD_SOCKS5=/localhost:9050 \
  PRIVOXY_TOGGLE=1 \
  PRIVOXY_ENABLE_REMOTE_TOGGLE=0 \
  PRIVOXY_ENABLE_EDIT_ACTIONS=0 \
  PRIVOXY_ENABLE_COMPRESSION=0 \
  PRIVOXY_ACCEPT_INTERCEPTED_REQUESTS=0 \
  PRIVOXY_BUFFER_LIMIT=4096 \
  PRIVOXY_ENABLE_PROXY_AUTHENTICATION_FORWARDING=0

# Default Tor configuration
ENV TOR_SOCKS_PORT=9050 \
  TOR_CONTROL_PORT=9051 \
  TOR_DNS_PORT=5353 \
  TOR_RELAY=0 \
  TOR_NICKNAME=torPrivoxy \
  TOR_BANDWIDTH_RATE=1000000 \
  TOR_BANDWIDTH_BURST=2000000 \
  TOR_EXIT_POLICY="reject *:*"

HEALTHCHECK --interval=60s --timeout=15s --start-period=20s \
  CMD nc -z localhost 8118 || exit 1

USER toruser

COPY service /etc/service/

ENTRYPOINT ["tini", "--"]
CMD ["runsvdir", "/etc/service"]
