#!/bin/sh

# Generate Privoxy configuration file
cat << EOF > /etc/privoxy/config
listen-address ${PRIVOXY_LISTEN_ADDRESS}
forward-socks5 ${PRIVOXY_FORWARD_SOCKS5} .
toggle ${PRIVOXY_TOGGLE}
enable-remote-toggle ${PRIVOXY_ENABLE_REMOTE_TOGGLE}
enable-edit-actions ${PRIVOXY_ENABLE_EDIT_ACTIONS}
enable-compression ${PRIVOXY_ENABLE_COMPRESSION}
accept-intercepted-requests ${PRIVOXY_ACCEPT_INTERCEPTED_REQUESTS}
buffer-limit ${PRIVOXY_BUFFER_LIMIT}
enable-proxy-authentication-forwarding ${PRIVOXY_ENABLE_PROXY_AUTHENTICATION_FORWARDING}
EOF

# Start Privoxy
exec privoxy --no-daemon /etc/privoxy/config
